import type { Metadata } from 'next';
import 'leaflet/dist/leaflet.css';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import dynamic from 'next/dynamic';

const NavBar = dynamic(() => import('@/components/Navbar'), { ssr: false });
const Footer = dynamic(() => import('@/components/Footer'), { ssr: false });
const Providers = dynamic(() => import('./providers'), { ssr: false });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js Application Template',
  description: 'Generated by ics-software-engineering.github.io',
};

// ...imports stay the same...

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${inter.className} wrapper`;

  const bodyStyle = {
    margin: 0,
    minHeight: '100vh',
    background:
      'radial-gradient(circle at 10% 0%, #0b1120 0%, #020617 55%, #000000 100%)',
    color: '#e5e7eb',
  };

  const contentWrapperStyle = {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
  };

  const mainWrapperStyle = {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    paddingBottom: 32, // ⬅️ added: space above the footer
  };

  return (
    <html lang="en">
      <body className={classString} style={bodyStyle}>
        <Providers>
          <div style={contentWrapperStyle}>
            <NavBar />
            <div style={mainWrapperStyle}>{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}