const fs = require('fs');
const path = require('path');

// Paths
const ZIP_LIST_FILE = path.join(__dirname, '..', 'output2.txt');       // your unique ZIP list
const ZIP_LATLON_CSV = path.join(__dirname, '..', 'us-zip-latlon.csv'); // your new dataset
const OUTPUT_TS_FILE = path.join(__dirname, '..', 'src', 'data', 'zipLocations.ts');

function main() {
  // 1) Load ZIPs from your list (already deduped)
  const zipListRaw = fs.readFileSync(ZIP_LIST_FILE, 'utf8');
  const zipSet = new Set(
    zipListRaw
      .split(/\r?\n/)
      .map(z => z.trim())
      .filter(z => z.length > 0)
  );

  console.log(`Loaded ${zipSet.size} ZIPs from output2.txt`);

  // 2) Read the semicolon-separated CSV
  const csvRaw = fs.readFileSync(ZIP_LATLON_CSV, 'utf8');
  const lines = csvRaw.split(/\r?\n/).filter(l => l.trim().length > 0);

  if (lines.length === 0) {
    throw new Error('us-zip-latlon.csv seems empty');
  }

  const zipLocationMap = {};
  let matched = 0;
  let totalLines = 0;

  for (const line of lines) {
    totalLines++;

    const cols = line.split(';');
    if (cols.length < 2) continue;

    // First column: ZIP (may be numeric or string)
    let rawZip = cols[0].trim();
    if (!rawZip) continue;

    // If it looks numeric (e.g., "33311" or "904" etc), keep as string and pad to 5 digits
    if (/^\d+$/.test(rawZip)) {
      rawZip = rawZip.padStart(5, '0');
    }

    // Skip header or rows we don't care about
    if (!zipSet.has(rawZip)) {
      continue;
    }

    // Last column: "lat, lon" string (e.g., "26.14412, -80.17331")
    let latLonStr = cols[cols.length - 1].trim();

    // Strip any surrounding quotes if present
    if (
      (latLonStr.startsWith('"') && latLonStr.endsWith('"')) ||
      (latLonStr.startsWith("'") && latLonStr.endsWith("'"))
    ) {
      latLonStr = latLonStr.slice(1, -1);
    }

    // Split by comma into [lat, lon]
    const parts = latLonStr.split(',');
    if (parts.length < 2) {
      // Not a valid "lat, lon" string
      continue;
    }

    const lat = parseFloat(parts[0].trim());
    const lon = parseFloat(parts[1].trim());

    if (Number.isNaN(lat) || Number.isNaN(lon)) {
      continue;
    }

    zipLocationMap[rawZip] = { lat, lon };
    matched++;
  }

  console.log(`Processed ${totalLines} lines from us-zip-latlon.csv`);
  console.log(`Matched ${matched} ZIPs with lat/lon`);

  const sortedZips = Object.keys(zipLocationMap).sort();

  // 3) Emit src/data/zipLocations.ts
  let out = '';
  out += '// AUTO-GENERATED FILE. Do not edit.\n';
  out += '// Generated by scripts/buildZipLocations.cjs\n\n';
  out += 'export const zipLocationMap: Record<string, { lat: number; lon: number }> = {\n';

  for (const z of sortedZips) {
    const { lat, lon } = zipLocationMap[z];
    out += `  "${z}": { lat: ${lat}, lon: ${lon} },\n`;
  }

  out += '};\n';

  fs.mkdirSync(path.dirname(OUTPUT_TS_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_TS_FILE, out, 'utf8');

  console.log(`Wrote ${sortedZips.length} ZIPs to ${OUTPUT_TS_FILE}`);
}

main();
